//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRescueTrackerSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodCollection
    {
        public int Id { get; set; }
        public System.DateTime RequestTime { get; set; }
        public string Address { get; set; }
        public System.DateTime DueTime { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ApprovalTime { get; set; }
        public Nullable<System.DateTime> CollectionTime { get; set; }
        public Nullable<System.DateTime> DistributionTime { get; set; }
        public string RequestCreatorEmail { get; set; }
        public string ApproverEmail { get; set; }
        public string DistributorEmail { get; set; }
    
        public virtual NGOAuthority NGOAuthority { get; set; }
        public virtual NGOEmployee NGOEmployee { get; set; }
        public virtual RestaurantAuthority RestaurantAuthority { get; set; }
    }
}
