//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRescueTrackerSystem.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodRescueTrackerSystemEntities : DbContext
    {
        public FoodRescueTrackerSystemEntities()
            : base("name=FoodRescueTrackerSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NGOAuthority> NGOAuthorities { get; set; }
        public virtual DbSet<NGOEmployee> NGOEmployees { get; set; }
        public virtual DbSet<RestaurantAuthority> RestaurantAuthorities { get; set; }
        public virtual DbSet<FoodCollection> FoodCollections { get; set; }
        public virtual DbSet<LicenseeKey> LicenseeKeys { get; set; }
    }
}
